### ISSUE TITLE
Plot take longer time to process and improve subplot

### ISSUE THREAD

**Issue by tasanyphy01773** [tasanyphy01773/CLIM680#1]
The Zarr format itself uses, extreme chunking and compression that's why when ploting a chunk of dataset it provides quick image. But when plotting for whole globe it takes longer time to plot one image. 

Subplot: Could be more improved.

**Comment by luisortizuriarte** [comment]
For large datasets we can often expect rendering of plots to take some time. Methods like pcolor are often faster, and there are libraries like Datashader that were designed to plot just enough data to be representative (https://datashader.org/getting_started/Introduction.html).

The comment on "subplot" could be more detailed!

**Comment by tasanyphy01773** [comment]
Thanks for the suggestion. The pcolor method is indeed slightly faster than the countourf. I have added both methods with a time magic for both cells. I have also improved the subplot. Reduced the gap between each point. The title and unit names are on there.
